import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const header = (
    <header>
      <Link href={'/'}>
        <h1 className="text-2xl">Halo 👋 Hafidz's Blog 💻</h1>
      </Link>
    </header>
  );

  const footer = (
    <footer>
      <Link href={'/'}>
        <h2>Built by Muhammad Hafidz</h2>
      </Link>
    </footer>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
